### ISSUE TITLE
Query on what operating system this is meant for

### ISSUE THREAD

**Issue by jamesanderson16** [andre0707/GCC-Helper#1]
Hi,

Is this for a computer or a phone (I'm guessing iPhone) interface?

Thanks

**Comment by andre0707** [comment]
Currently this is a macOS app only.
It can be downloaded as a compiled app in the [release section](https://github.com/andre0707/GCC-Helper/releases) or you can download the project and compile it on your own Mac.

**Comment by jamesanderson16** [comment]
Can I note be added to the read me file please 😊

**Comment by andre0707** [comment]
Sorry, I'm not sure what you want me to add to the readme file

**Comment by jamesanderson16** [comment]
Can you add that the app is a macOS app 😊

**Comment by andre0707** [comment]
got it. 
Added platform availability to the read me and about section.
